[[main]]
  name = "GitHub"
  url = "https://github.com/henkisdabro/"
  weight = 10

[[sociallinkedin]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henriksoderlund/"
  weight = 20
  icon = "linkedin"

[[socialtwitter]]
  name = "Twitter"
  url = "https://twitter.com/henkis/"
  weight = 30