[[main]]
  name = "GitHub"
  url = "https://github.com/henkidabro"
  weight = 10

[[social]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/henriksoderlund/"
  weight = 20

[[social]]
  name = "Twitter"
  url = "https://twitter.com/henkis"
  weight = 30
