# Meta Data for SEO

## Homepage
title = "Henrik Söderlund"
titleSeparator = "-"
titleAddition = "Modern Hugo Starter"
description = "A personal showcase"

## Open Graph
images = ["hyas.png"]
ogLocale = "en_US"
titleHome = "Hyas Hugo Starter"

## Twitter Cards
twitterSite = "@henkis"
twitterCreator = "@henkis"

## JSON-LD
schemaType = "Person"
# schemaType = "Organization"
schemaName = "Henrik Söderlund"
schemaAuthor = "Henrik Söderlund"
schemaAuthorTwitter = "https://twitter.com/henkis"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/henriksoderlund/"
schemaAuthorGitHub = "https://github.com/henkis"
schemaLocale = "en-US"
schemaLogo = "logo-hyas.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "hyas.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/henkis"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/henkisdabro/"

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "320"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1280x720 Center" # normalize image size

# Footer
footer = "Powered by <a href=\"https://pages.cloudflare.com/\">Cloudflare Pages</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://gethyas.com/\">Hyas</a>"

# Feed
copyRight = "Copyright (c) 2022 Henrik Söderlund"

# Alert
alert = false
alertDismissable = true
alertText = "Deliver web projects 10x faster. <a class=\"alert-link\" href=\"https://www.netlify.com/whitepaper/\" target=\"_blank\" rel=\"noopener\">Get the free enterprise paper →</a>"
